// Generated by scripts/generate-f0-artifacts.ts. Do not edit.
export const generatedMockosHttpOperations = {
  configure_environment: {
    method: "PUT",
    operationId: "configure_environment",
    path: "/environments/{environmentId}",
    requiredScopes: ["env:rw"],
    retry: "idempotent",
    successStatus: 200,
  },
  create_application: {
    method: "POST",
    operationId: "create_application",
    path: "/environments/{environmentId}/applications",
    requiredScopes: ["env:rw"],
    retry: "never",
    successStatus: 201,
  },
  delete_environment: {
    method: "DELETE",
    operationId: "delete_environment",
    path: "/environments/{environmentId}",
    requiredScopes: ["env:rw"],
    retry: "idempotent",
    successStatus: 204,
  },
  get_environment_discovery: {
    method: "GET",
    operationId: "get_environment_discovery",
    path: "/environments/{environmentId}/well-known",
    requiredScopes: ["env:ro"],
    retry: "safe",
    successStatus: 200,
  },
  seed_identities: {
    method: "POST",
    operationId: "seed_identities",
    path: "/environments/{environmentId}/identities:seed",
    requiredScopes: ["env:rw"],
    retry: "never",
    successStatus: 200,
  },
} as const;

export type GeneratedMockosHttpOperationId = keyof typeof generatedMockosHttpOperations;
