#!/usr/bin/env tsx

import {
  generateMockosHttpOperationManifest,
  generateMockosManagementOpenApi,
} from "../packages/openapi/src/index";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

const canonicalize = (value: unknown): JsonValue => {
  if (
    value === null ||
    typeof value === "boolean" ||
    typeof value === "number" ||
    typeof value === "string"
  ) {
    return value;
  }
  if (Array.isArray(value)) return value.map(canonicalize);
  if (typeof value !== "object") {
    throw new Error(`Cannot canonicalize ${typeof value}.`);
  }
  const object: Record<string, JsonValue> = {};
  for (const key of Object.keys(value).sort()) {
    object[key] = canonicalize(Reflect.get(value, key));
  }
  return object;
};

const stableJson = (value: unknown): string =>
  `${JSON.stringify(canonicalize(value), null, 2)}\n`;

const generatedClientManifest = (): string => {
  const manifest = generateMockosHttpOperationManifest();
  const lines = [
    "// Generated by scripts/generate-f0-artifacts.ts. Do not edit.",
    "export const generatedMockosHttpOperations = {",
  ];
  for (const [operationId, operation] of Object.entries(manifest).sort(
    ([left], [right]) => left.localeCompare(right)
  )) {
    lines.push(
      `  ${operationId}: {`,
      `    method: ${JSON.stringify(operation.method)},`,
      `    operationId: ${JSON.stringify(operation.operationId)},`,
      `    path: ${JSON.stringify(operation.path)},`,
      `    requiredScopes: ${JSON.stringify(operation.requiredScopes)},`,
      `    retry: ${JSON.stringify(operation.retry)},`,
      `    successStatus: ${operation.successStatus},`,
      "  },"
    );
  }
  lines.push(
    "} as const;",
    "",
    "export type GeneratedMockosHttpOperationId = keyof typeof generatedMockosHttpOperations;",
    ""
  );
  return lines.join("\n");
};

const openApiPath = resolve(
  process.cwd(),
  "packages/openapi/openapi/mockos-management.v1.json"
);
const clientManifestPath = resolve(process.cwd(), "packages/client/src/generated.ts");

const openApiContents = stableJson(generateMockosManagementOpenApi());
const clientManifestContents = generatedClientManifest();

const artifacts = [
  { path: openApiPath, contents: openApiContents },
  { path: clientManifestPath, contents: clientManifestContents },
];

if (process.argv.includes("--check")) {
  const drift: string[] = [];
  for (const artifact of artifacts) {
    const current = await readFile(artifact.path, "utf8").catch(() => "");
    if (current !== artifact.contents) {
      drift.push(artifact.path.slice(process.cwd().length + 1));
    }
  }
  if (drift.length > 0) {
    throw new Error(
      `F0 generated artifacts are stale: ${drift.join(", ")}. Run pnpm f0:generate.`
    );
  }
  process.stdout.write("PASS  F0 generated artifacts match the operation registry\n");
} else {
  for (const artifact of artifacts) {
    await mkdir(dirname(artifact.path), { recursive: true });
    await writeFile(artifact.path, artifact.contents);
  }
  process.stdout.write("WROTE F0 OpenAPI and client operation artifacts\n");
}
