#!/usr/bin/env tsx

import {
  generateMockosHttpOperationManifest,
  generateMockosManagementDocumentationCatalog,
  generateMockosManagementOpenApi,
  type MockosManagementDocumentationCatalog,
  type MockosManagementDocumentationTool,
} from "../packages/openapi/src/index";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, posix, resolve } from "node:path";

type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

type Artifact = {
  path: string;
  contents: string;
};

const DOCUMENTATION_LAST_REVIEWED = "2026-07-23";

const canonicalize = (value: unknown): JsonValue => {
  if (
    value === null ||
    typeof value === "boolean" ||
    typeof value === "number" ||
    typeof value === "string"
  ) {
    return value;
  }
  if (Array.isArray(value)) return value.map(canonicalize);
  if (typeof value !== "object") {
    throw new Error(`Cannot canonicalize ${typeof value}.`);
  }
  const object: Record<string, JsonValue> = {};
  for (const key of Object.keys(value).sort()) {
    object[key] = canonicalize(Reflect.get(value, key));
  }
  return object;
};

const stableJson = (value: unknown): string =>
  `${JSON.stringify(canonicalize(value), null, 2)}\n`;

const generatedClientManifest = (): string => {
  const manifest = generateMockosHttpOperationManifest();
  const lines = [
    "// Generated by scripts/generate-f0-artifacts.ts. Do not edit.",
    "export const generatedMockosHttpOperations = {",
  ];
  for (const [operationId, operation] of Object.entries(manifest).sort(
    ([left], [right]) => left.localeCompare(right)
  )) {
    lines.push(
      `  ${operationId}: {`,
      `    method: ${JSON.stringify(operation.method)},`,
      `    operationId: ${JSON.stringify(operation.operationId)},`,
      `    path: ${JSON.stringify(operation.path)},`,
      `    requiredScopes: ${JSON.stringify(operation.requiredScopes)},`,
      `    retry: ${JSON.stringify(operation.retry)},`,
      `    successStatus: ${operation.successStatus},`,
      "  },"
    );
  }
  lines.push(
    "} as const;",
    "",
    "export type GeneratedMockosHttpOperationId = keyof typeof generatedMockosHttpOperations;",
    ""
  );
  return lines.join("\n");
};

const tableCell = (value: string): string =>
  value.replaceAll("|", "\\|").replaceAll("\n", " ");

const secretPolicy = (tool: MockosManagementDocumentationTool): string => {
  const policies = [
    tool.secrets.request === "none" ? null : `request ${tool.secrets.request}`,
    tool.secrets.response === "none" ? null : `response ${tool.secrets.response}`,
  ].filter((value): value is string => value !== null);
  return policies.length === 0 ? "none" : policies.join("; ");
};

const httpSummary = (tool: MockosManagementDocumentationTool): string =>
  tool.http ? `\`${tool.http.method} /__mockos/v1${tool.http.path}\`` : "MCP only";

const renderManagementTools = (
  catalog: MockosManagementDocumentationCatalog
): string => {
  const lines = [
    "# Management MCP tool reference",
    "",
    "Status: Generated from the implemented 15-tool management registry; F1 mock MCP is unavailable",
    `Last reviewed: ${DOCUMENTATION_LAST_REVIEWED}`,
    "",
    "<!-- Generated by scripts/generate-f0-artifacts.ts. Do not edit. -->",
    "",
    "This reference is generated from",
    "[`packages/contracts/src/operations/management.ts`](../../packages/contracts/src/operations/management.ts).",
    "Change the canonical schemas or metadata, run `pnpm f0:generate`, and commit the",
    "result. The [machine-readable catalog](./management-operations.v1.json) contains",
    "the same metadata and JSON Schemas.",
    "",
    `The current management MCP server exposes **${catalog.managementMcp.toolCount} tools**.`,
    `Exactly **${catalog.selfHostedHttp.routeCount}** of those operations also have an`,
    "implemented self-hosted HTTP route. An MCP-only tool must not be called through an",
    "invented HTTP path.",
    "",
    "> `env:ro` and `env:rw` are contract metadata, not enforced scoped-key permissions.",
    "> F4 owns shared scope enforcement and its security evidence.",
    "",
    "## Catalog",
    "",
    "| Tool | Effect | Retry | Secret handling | HTTP availability |",
    "| --- | --- | --- | --- | --- |",
  ];

  for (const tool of catalog.managementMcp.tools) {
    lines.push(
      `| [\`${tool.operationId}\`](#${tool.operationId}) | ${tool.effect} | ${tool.retry} | ${tableCell(secretPolicy(tool))} | ${httpSummary(tool)} |`
    );
  }

  lines.push(
    "",
    "## Transport and result contract",
    "",
    "- Transport: Streamable HTTP at `/mcp`.",
    `- Tested protocol revision: \`${catalog.managementMcp.testedProtocolVersion}\`.`,
    "- Standalone GET stream: unsupported; `GET /mcp` returns `405`.",
    "- Successful tools return text content plus structured content shaped as",
    "  `{ data, meta: { requestId } }`.",
    "- Handler failures return an MCP error result containing an RFC 7807 problem.",
    "- SDK input-schema failures happen before handler entry and use the SDK validation",
    "  error shape.",
    "- Saved automation should pass an explicit `environmentId`; the current-environment",
    "  cursor is transport-session-local.",
    "",
    "## Tools",
    ""
  );

  for (const tool of catalog.managementMcp.tools) {
    const annotations = tool.mcp.annotations;
    lines.push(
      `<a id="${tool.operationId}"></a>`,
      "",
      `### \`${tool.operationId}\``,
      "",
      `**${tool.title}.** ${tool.description}`,
      "",
      `- Scope metadata: ${tool.requiredScopes.map((scope) => `\`${scope}\``).join(", ")}`,
      `- Effect: \`${tool.effect}\``,
      `- Retry policy: \`${tool.retry}\``,
      `- Secret handling: ${secretPolicy(tool)}`,
      `- HTTP: ${httpSummary(tool)}`,
      `- MCP annotations: read-only \`${annotations.readOnlyHint}\`, destructive \`${annotations.destructiveHint}\`, idempotent \`${annotations.idempotentHint}\`, open-world \`${annotations.openWorldHint}\``,
      "",
      "<details>",
      "<summary>Input JSON Schema</summary>",
      "",
      "```json",
      stableJson(tool.mcp.inputSchema).trimEnd(),
      "```",
      "",
      "</details>",
      "",
      "<details>",
      "<summary>Structured result JSON Schema</summary>",
      "",
      "```json",
      stableJson(tool.mcp.outputSchema).trimEnd(),
      "```",
      "",
      "</details>",
      ""
    );
  }

  lines.push(
    "## Unavailable MCP surfaces",
    "",
    "- Environment-hosted mock MCP servers are planned for F1 and do not exist in this",
    "  source.",
    "- Mock OpenAI and Anthropic APIs are planned for F2 and do not exist in this source.",
    "- Code Mode `search` and `execute` are planned for F6 and remain disabled.",
    "",
    "Use [implementation status](../IMPLEMENTATION_STATUS.md) for evidence and the",
    "[interface model](../concepts/interface-model.md) for the distinction between",
    "management MCP and future mock MCP workloads.",
    ""
  );

  return lines.join("\n");
};

const renderSelfHostedHttp = (
  catalog: MockosManagementDocumentationCatalog
): string => {
  const lines = [
    "# Self-hosted management HTTP reference",
    "",
    "Status: Generated reference for the five implemented public Worker management routes",
    `Last reviewed: ${DOCUMENTATION_LAST_REVIEWED}`,
    "",
    "<!-- Generated by scripts/generate-f0-artifacts.ts. Do not edit. -->",
    "",
    "The public Worker exposes a deliberately narrow management HTTP surface under",
    `\`${catalog.selfHostedHttp.basePath}\`. It is a supporting interface, not an HTTP`,
    "copy of the 15-tool management MCP server.",
    "",
    `Exactly **${catalog.selfHostedHttp.routeCount} routes** are implemented:`,
    "",
    "| Operation ID | Management operation | Method and path | Success |",
    "| --- | --- | --- | --- |",
  ];

  for (const operation of catalog.selfHostedHttp.operations) {
    lines.push(
      `| \`${operation.operationId}\` | \`${operation.managementOperationId}\` | \`${operation.method} ${catalog.selfHostedHttp.basePath}${operation.path}\` | \`${operation.successStatus}\` |`
    );
  }

  lines.push(
    "",
    "The deterministic",
    "[OpenAPI 3.0 document](../../packages/openapi/openapi/mockos-management.v1.json)",
    "contains the exact request, response, path, and query schemas. The generated",
    "`@mockos/client` skeleton authorizes only this operation map.",
    "",
    "## Authentication",
    "",
    "Self-hosting requires the Worker `API_KEY` secret. Missing server configuration",
    "fails closed with `503 CONTROL_API_UNAVAILABLE`; a missing or incorrect presented",
    "key returns `401 UNAUTHORIZED`.",
    "",
    "Use an inert environment-variable reference rather than a literal key:",
    "",
    "```sh",
    "curl --fail-with-body \\",
    '  --header "Authorization: Bearer $MOCKOS_API_KEY" \\',
    '  "$MOCKOS_ORIGIN/__mockos/v1/environments/$MOCKOS_ENVIRONMENT_ID/well-known?issuer_base=$MOCKOS_ORIGIN"',
    "```",
    "",
    "`X-API-Key` is accepted by the direct public Worker, but an operated service may",
    "require Bearer authentication and a different account-key format. Follow the",
    "operator's exact endpoint and authentication contract.",
    "",
    "Management keys never belong on SCIM, Graph-shaped, Okta directory-shaped, Authn,",
    "or outbound target requests.",
    "",
    "## Deliberate limits",
    "",
    "- There is no direct HTTP route for listing environments, minting tokens, running",
    "  provisioning, setting scenarios, inspecting/asserting logs, simulating lifecycle,",
    "  or selecting a session cursor.",
    "- The HTTP `get_environment_discovery` operation returns an OIDC discovery document;",
    "  the MCP `get_wellknown_urls` tool returns a broader endpoint summary.",
    "- HTTP routes always require an explicit environment ID.",
    "- `env:ro` and `env:rw` remain metadata until F4; they are not currently enforced",
    "  key scopes.",
    "- The client and OpenAPI packages are not distribution-qualified or published.",
    "",
    "Use the [management MCP reference](./management-tools.md) when the workflow needs",
    "the complete current management surface.",
    ""
  );

  return lines.join("\n");
};

const renderLlmsIndex = (catalog: MockosManagementDocumentationCatalog): string =>
  [
    "# mockOS",
    "",
    "> MCP-first deterministic Entra ID and Okta test infrastructure. Agents and",
    "> automation control synthetic environments through management MCP; applications",
    "> under test call the returned provider-shaped endpoints.",
    "",
    "## Start",
    "",
    "- [Documentation index](docs/README.md): task-oriented map for humans and agents.",
    "- [MCP-first quickstart](docs/getting-started/mcp-first.md): connect, discover,",
    "  create, test, assert, and clean up.",
    "- [Interface model](docs/concepts/interface-model.md): management MCP versus",
    "  provider endpoints, HTTP, CLI, console, and future mock MCP.",
    "- [Management tool reference](docs/reference/management-tools.md): generated",
    `  reference for all ${catalog.managementMcp.toolCount} current MCP tools.`,
    "- [Machine operation catalog](docs/reference/management-operations.v1.json):",
    "  generated schemas and capability metadata.",
    "- [Self-hosted HTTP reference](docs/reference/self-hosted-http.md): generated",
    `  reference for the ${catalog.selfHostedHttp.routeCount} implemented HTTP routes.`,
    "",
    "## Current capability boundary",
    "",
    `- Management MCP: implemented at \`${catalog.managementMcp.path}\` with`,
    `  ${catalog.managementMcp.toolCount} tools over ${catalog.managementMcp.transport}.`,
    `- Tested MCP revision: \`${catalog.managementMcp.testedProtocolVersion}\`;`,
    "  standalone GET streaming is unsupported.",
    `- Self-hosted management HTTP: ${catalog.selfHostedHttp.routeCount} implemented`,
    `  routes under \`${catalog.selfHostedHttp.basePath}\`.`,
    "- `env:ro` and `env:rw`: metadata only, not enforced scoped-key permissions.",
    "- F1 mock MCP servers: unavailable.",
    "- F2 mock LLM APIs: unavailable.",
    "- F3 script execution: unavailable; `NoSandbox` fails closed.",
    "- F6 Code Mode `search` and `execute`: unavailable and disabled.",
    "- CLI and typed client: unpublished.",
    "",
    "## Safety and evidence",
    "",
    "- [Known limitations](docs/known-limitations.md)",
    "- [Implementation status](docs/IMPLEMENTATION_STATUS.md)",
    "- [Threat model](docs/security/threat-model.md)",
    "- [Requirements traceability](docs/requirements-traceability.md)",
    "- Never put management keys, real identities, real provider tokens, or customer",
    "  data in fixtures, logs, examples, or reports.",
    "- Source, deployed mock acceptance, and verified-live provider evidence are",
    "  independent claims. No current fixture is verified-live.",
    "",
    "## More context",
    "",
    "- [Curated full agent context](llms-full.txt)",
    "- [Public repository README](README.md)",
    "- [Testing skill](skills/mockos-testing/SKILL.md)",
    "",
  ].join("\n");

const rewriteRelativeMarkdownLinksForRoot = (
  contents: string,
  sourcePath: string
): string =>
  contents.replace(
    /(\]\()((?!https?:\/\/|mailto:|#|\/)[^)\s]+)(\))/g,
    (_match, prefix: string, target: string, suffix: string) => {
      const hashIndex = target.indexOf("#");
      const path = hashIndex === -1 ? target : target.slice(0, hashIndex);
      const hash = hashIndex === -1 ? "" : target.slice(hashIndex);
      const rooted = posix.normalize(posix.join(posix.dirname(sourcePath), path));
      return `${prefix}${rooted}${hash}${suffix}`;
    }
  );

const renderLlmsFull = async (generated: {
  managementTools: string;
  selfHostedHttp: string;
}): Promise<string> => {
  const sources = [
    { title: "Project README", path: "README.md" },
    {
      title: "MCP-first quickstart",
      path: "docs/getting-started/mcp-first.md",
    },
    {
      title: "Interface model",
      path: "docs/concepts/interface-model.md",
    },
    {
      title: "Management MCP behavior",
      path: "docs/mcp.md",
    },
    {
      title: "Known limitations",
      path: "docs/known-limitations.md",
    },
    {
      title: "Implementation status",
      path: "docs/IMPLEMENTATION_STATUS.md",
    },
    {
      title: "Threat model",
      path: "docs/security/threat-model.md",
    },
  ];

  const sections = await Promise.all(
    sources.map(async ({ title, path }) => {
      const contents = await readFile(resolve(process.cwd(), path), "utf8");
      return [
        `# Source: ${title}`,
        "",
        `Repository path: \`${path}\``,
        "",
        rewriteRelativeMarkdownLinksForRoot(contents.trim(), path),
      ].join("\n");
    })
  );

  sections.splice(
    3,
    0,
    [
      "# Source: Generated management MCP tool reference",
      "",
      "Repository path: `docs/reference/management-tools.md`",
      "",
      rewriteRelativeMarkdownLinksForRoot(
        generated.managementTools.trim(),
        "docs/reference/management-tools.md"
      ),
    ].join("\n"),
    [
      "# Source: Generated self-hosted HTTP reference",
      "",
      "Repository path: `docs/reference/self-hosted-http.md`",
      "",
      rewriteRelativeMarkdownLinksForRoot(
        generated.selfHostedHttp.trim(),
        "docs/reference/self-hosted-http.md"
      ),
    ].join("\n")
  );

  return [
    "# mockOS curated full agent context",
    "",
    "Generated by `scripts/generate-f0-artifacts.ts`. This file combines public,",
    "reviewed product guidance. It does not add capabilities, deployment evidence,",
    "credentials, private operated-service material, or verified-live provider claims.",
    "",
    "Start with `llms.txt` when the compact map is sufficient.",
    "",
    ...sections.flatMap((section) => ["---", "", section, ""]),
  ].join("\n");
};

const openApiPath = resolve(
  process.cwd(),
  "packages/openapi/openapi/mockos-management.v1.json"
);
const clientManifestPath = resolve(process.cwd(), "packages/client/src/generated.ts");
const documentationCatalogPath = resolve(
  process.cwd(),
  "docs/reference/management-operations.v1.json"
);
const managementToolsPath = resolve(
  process.cwd(),
  "docs/reference/management-tools.md"
);
const selfHostedHttpPath = resolve(process.cwd(), "docs/reference/self-hosted-http.md");
const llmsPath = resolve(process.cwd(), "llms.txt");
const llmsFullPath = resolve(process.cwd(), "llms-full.txt");

const documentationCatalog = generateMockosManagementDocumentationCatalog();
const managementToolsContents = renderManagementTools(documentationCatalog);
const selfHostedHttpContents = renderSelfHostedHttp(documentationCatalog);

const artifacts: Artifact[] = [
  {
    path: openApiPath,
    contents: stableJson(generateMockosManagementOpenApi()),
  },
  {
    path: clientManifestPath,
    contents: generatedClientManifest(),
  },
  {
    path: documentationCatalogPath,
    contents: stableJson(documentationCatalog),
  },
  {
    path: managementToolsPath,
    contents: managementToolsContents,
  },
  {
    path: selfHostedHttpPath,
    contents: selfHostedHttpContents,
  },
  {
    path: llmsPath,
    contents: renderLlmsIndex(documentationCatalog),
  },
  {
    path: llmsFullPath,
    contents: await renderLlmsFull({
      managementTools: managementToolsContents,
      selfHostedHttp: selfHostedHttpContents,
    }),
  },
];

if (process.argv.includes("--check")) {
  const drift: string[] = [];
  for (const artifact of artifacts) {
    const current = await readFile(artifact.path, "utf8").catch(() => "");
    if (current !== artifact.contents) {
      drift.push(artifact.path.slice(process.cwd().length + 1));
    }
  }
  if (drift.length > 0) {
    throw new Error(
      `F0 generated artifacts are stale: ${drift.join(", ")}. Run pnpm f0:generate.`
    );
  }
  process.stdout.write(
    "PASS  F0 OpenAPI, client, and MCP-first documentation artifacts match the operation registry\n"
  );
} else {
  for (const artifact of artifacts) {
    await mkdir(dirname(artifact.path), { recursive: true });
    await writeFile(artifact.path, artifact.contents);
  }
  process.stdout.write(
    "WROTE F0 OpenAPI, client, and MCP-first documentation artifacts\n"
  );
}
